"""Add DocumentoCliente

Revision ID: 360b04208e54
Revises: e06e0922c3e4
Create Date: 2026-02-27 08:39:48.458334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '360b04208e54'
down_revision: Union[str, Sequence[str], None] = 'e06e0922c3e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentos_cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escritorio_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('arquivo_path', sa.String(length=300), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['escritorio_id'], ['escritorios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_cliente_cliente_id'), 'documentos_cliente', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_documentos_cliente_escritorio_id'), 'documentos_cliente', ['escritorio_id'], unique=False)
    op.create_index(op.f('ix_documentos_cliente_id'), 'documentos_cliente', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documentos_cliente_id'), table_name='documentos_cliente')
    op.drop_index(op.f('ix_documentos_cliente_escritorio_id'), table_name='documentos_cliente')
    op.drop_index(op.f('ix_documentos_cliente_cliente_id'), table_name='documentos_cliente')
    op.drop_table('documentos_cliente')
    # ### end Alembic commands ###
