"""Add ModeloDocumento

Revision ID: e06e0922c3e4
Revises: fe8def6a51ad
Create Date: 2026-02-26 16:26:07.252372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e06e0922c3e4'
down_revision: Union[str, Sequence[str], None] = 'fe8def6a51ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modelos_documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escritorio_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('arquivo_path', sa.String(length=300), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['escritorio_id'], ['escritorios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modelos_documento_escritorio_id'), 'modelos_documento', ['escritorio_id'], unique=False)
    op.create_index(op.f('ix_modelos_documento_id'), 'modelos_documento', ['id'], unique=False)
    op.alter_column('partes_envolvidas', 'data_cadastro',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('partes_envolvidas_escritorio_id_fkey'), 'partes_envolvidas', type_='foreignkey')
    op.drop_constraint(op.f('partes_envolvidas_cliente_id_fkey'), 'partes_envolvidas', type_='foreignkey')
    op.create_foreign_key(None, 'partes_envolvidas', 'clientes', ['cliente_id'], ['id'])
    op.create_foreign_key(None, 'partes_envolvidas', 'escritorios', ['escritorio_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'partes_envolvidas', type_='foreignkey')
    op.drop_constraint(None, 'partes_envolvidas', type_='foreignkey')
    op.create_foreign_key(op.f('partes_envolvidas_cliente_id_fkey'), 'partes_envolvidas', 'clientes', ['cliente_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('partes_envolvidas_escritorio_id_fkey'), 'partes_envolvidas', 'escritorios', ['escritorio_id'], ['id'], ondelete='CASCADE')
    op.alter_column('partes_envolvidas', 'data_cadastro',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_modelos_documento_id'), table_name='modelos_documento')
    op.drop_index(op.f('ix_modelos_documento_escritorio_id'), table_name='modelos_documento')
    op.drop_table('modelos_documento')
    # ### end Alembic commands ###
