"""Add clientes and servicos

Revision ID: fe8def6a51ad
Revises: 0222f26a7915
Create Date: 2026-02-25 16:47:07.224504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe8def6a51ad'
down_revision: Union[str, Sequence[str], None] = '0222f26a7915'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escritorio_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('documento', sa.String(length=50), nullable=True),
    sa.Column('telefone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('cep', sa.String(length=20), nullable=True),
    sa.Column('data_nascimento', sa.String(length=20), nullable=True),
    sa.Column('nacionalidade', sa.String(length=100), nullable=True),
    sa.Column('estado_civil', sa.String(length=50), nullable=True),
    sa.Column('profissao', sa.String(length=100), nullable=True),
    sa.Column('rg', sa.String(length=50), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['escritorio_id'], ['escritorios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_table('servicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escritorio_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('tipo_servico_id', sa.Integer(), nullable=True),
    sa.Column('processo_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('valor_total', sa.Float(), nullable=True),
    sa.Column('condicoes_pagamento', sa.Text(), nullable=True),
    sa.Column('forma_pagamento', sa.String(length=100), nullable=True),
    sa.Column('qtd_parcelas', sa.Integer(), nullable=True),
    sa.Column('detalhes_pagamento', sa.Text(), nullable=True),
    sa.Column('porcentagem_exito', sa.String(length=20), nullable=True),
    sa.Column('data_contrato', sa.String(length=20), nullable=True),
    sa.Column('data_contratacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['escritorio_id'], ['escritorios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servicos_id'), 'servicos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_servicos_id'), table_name='servicos')
    op.drop_table('servicos')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
