"""Add servico_id to Processo

Revision ID: 0ffc78776994
Revises: 9b1f25a5a25d
Create Date: 2026-03-04 12:38:04.863673

"""
"""Add servico_id to Processo

Revision ID: 0ffc78776994
Revises: 9b1f25a5a25d
Create Date: 2026-03-04 12:38:04.863673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ffc78776994'
down_revision: Union[str, Sequence[str], None] = '9b1f25a5a25d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documentos_cliente', sa.Column('data_alteracao', sa.DateTime(), nullable=True, server_default=sa.text('CURRENT_TIMESTAMP')))
    op.add_column('modelos_documento', sa.Column('data_alteracao', sa.DateTime(), nullable=True, server_default=sa.text('CURRENT_TIMESTAMP')))
    # op.create_index(op.f('ix_movimentacoes_id'), 'movimentacoes', ['id'], unique=False)
    op.create_index(op.f('ix_pastas_documento_processo_id'), 'pastas_documento', ['processo_id'], unique=False)
    op.create_foreign_key(None, 'pastas_documento', 'processos', ['processo_id'], ['id'])
    # op.drop_index(op.f('idx_pastas_trabalho_escritorio'), table_name='pastas_trabalho')
    # op.create_index(op.f('ix_pastas_trabalho_escritorio_id'), 'pastas_trabalho', ['escritorio_id'], unique=False)
    # op.create_index(op.f('ix_pastas_trabalho_id'), 'pastas_trabalho', ['id'], unique=False)
    # op.create_index(op.f('ix_processo_assuntos_id'), 'processo_assuntos', ['id'], unique=False)
    # op.create_index(op.f('ix_processo_partes_id'), 'processo_partes', ['id'], unique=False)
    op.add_column('processos', sa.Column('servico_id', sa.Integer(), nullable=True))
    # op.drop_index(op.f('idx_processos_cliente'), table_name='processos')
    # op.drop_index(op.f('idx_processos_escritorio'), table_name='processos')
    # op.drop_index(op.f('idx_processos_numero'), table_name='processos')
    # op.create_index(op.f('ix_processos_cliente_id'), 'processos', ['cliente_id'], unique=False)
    # op.create_index(op.f('ix_processos_escritorio_id'), 'processos', ['escritorio_id'], unique=False)
    # op.create_index(op.f('ix_processos_id'), 'processos', ['id'], unique=False)
    # op.create_index(op.f('ix_processos_numero_processo'), 'processos', ['numero_processo'], unique=False)
    op.create_foreign_key(None, 'processos', 'servicos', ['servico_id'], ['id'], ondelete='SET NULL')
    # op.create_foreign_key(None, 'servicos', 'tipos_servico', ['tipo_servico_id'], ['id'])
    # op.create_foreign_key(None, 'servicos', 'processos', ['processo_id'], ['id'])
    # op.drop_index(op.f('idx_tipos_servico_escritorio'), table_name='tipos_servico')
    # op.create_index(op.f('ix_tipos_servico_escritorio_id'), 'tipos_servico', ['escritorio_id'], unique=False)
    # op.create_index(op.f('ix_tipos_servico_id'), 'tipos_servico', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_tipos_servico_id'), table_name='tipos_servico')
    # op.drop_index(op.f('ix_tipos_servico_escritorio_id'), table_name='tipos_servico')
    # op.create_index(op.f('idx_tipos_servico_escritorio'), 'tipos_servico', ['escritorio_id'], unique=False)
    # op.drop_constraint(None, 'servicos', type_='foreignkey')
    # op.drop_constraint(None, 'servicos', type_='foreignkey')
    op.drop_constraint(None, 'processos', type_='foreignkey')
    # op.drop_index(op.f('ix_processos_numero_processo'), table_name='processos')
    # op.drop_index(op.f('ix_processos_id'), table_name='processos')
    # op.drop_index(op.f('ix_processos_escritorio_id'), table_name='processos')
    # op.drop_index(op.f('ix_processos_cliente_id'), table_name='processos')
    # op.create_index(op.f('idx_processos_numero'), 'processos', ['numero_processo'], unique=False)
    # op.create_index(op.f('idx_processos_escritorio'), 'processos', ['escritorio_id'], unique=False)
    # op.create_index(op.f('idx_processos_cliente'), 'processos', ['cliente_id'], unique=False)
    op.drop_column('processos', 'servico_id')
    # op.drop_index(op.f('ix_processo_partes_id'), table_name='processo_partes')
    # op.drop_index(op.f('ix_processo_assuntos_id'), table_name='processo_assuntos')
    # op.drop_index(op.f('ix_pastas_trabalho_id'), table_name='pastas_trabalho')
    # op.drop_index(op.f('ix_pastas_trabalho_escritorio_id'), table_name='pastas_trabalho')
    # op.create_index(op.f('idx_pastas_trabalho_escritorio'), 'pastas_trabalho', ['escritorio_id'], unique=False)
    op.drop_constraint(None, 'pastas_documento', type_='foreignkey')
    op.drop_index(op.f('ix_pastas_documento_processo_id'), table_name='pastas_documento')
    # op.drop_index(op.f('ix_movimentacoes_id'), table_name='movimentacoes')
    op.drop_column('modelos_documento', 'data_alteracao')
    op.drop_column('documentos_cliente', 'data_alteracao')
    # ### end Alembic commands ###
