"""Add transacoes table

Revision ID: 21f5bd31cd3f
Revises: b9198114d446
Create Date: 2026-03-07 20:28:10.338193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21f5bd31cd3f'
down_revision: Union[str, Sequence[str], None] = 'b9198114d446'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escritorio_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('processo_id', sa.Integer(), nullable=True),
    sa.Column('servico_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('data_vencimento', sa.DateTime(), nullable=False),
    sa.Column('data_pagamento', sa.DateTime(), nullable=True),
    sa.Column('forma_pagamento', sa.String(length=100), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['escritorio_id'], ['escritorios.id'], ),
    sa.ForeignKeyConstraint(['processo_id'], ['processos.id'], ),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transacoes_cliente_id'), 'transacoes', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_transacoes_escritorio_id'), 'transacoes', ['escritorio_id'], unique=False)
    op.create_index(op.f('ix_transacoes_id'), 'transacoes', ['id'], unique=False)
    op.create_index(op.f('ix_transacoes_processo_id'), 'transacoes', ['processo_id'], unique=False)
    op.create_index(op.f('ix_transacoes_servico_id'), 'transacoes', ['servico_id'], unique=False)
    op.create_foreign_key(None, 'servicos', 'tipos_servico', ['tipo_servico_id'], ['id'])
    op.create_foreign_key(None, 'servicos', 'processos', ['processo_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'servicos', type_='foreignkey')
    op.drop_constraint(None, 'servicos', type_='foreignkey')
    op.drop_index(op.f('ix_transacoes_servico_id'), table_name='transacoes')
    op.drop_index(op.f('ix_transacoes_processo_id'), table_name='transacoes')
    op.drop_index(op.f('ix_transacoes_id'), table_name='transacoes')
    op.drop_index(op.f('ix_transacoes_escritorio_id'), table_name='transacoes')
    op.drop_index(op.f('ix_transacoes_cliente_id'), table_name='transacoes')
    op.drop_table('transacoes')
    # ### end Alembic commands ###
