"""add_analise_ia_fields

Revision ID: 384dfab6e868
Revises: 43c8f2f3e6d5
Create Date: 2026-04-13 15:42:45.837615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '384dfab6e868'
down_revision: Union[str, Sequence[str], None] = '43c8f2f3e6d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processos', sa.Column('analise_ia', sa.Text(), nullable=True))
    op.add_column('processos', sa.Column('data_analise_ia', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processos', 'data_analise_ia')
    op.drop_column('processos', 'analise_ia')
    # ### end Alembic commands ###
