"""Add password reset tokens

Revision ID: 43c8f2f3e6d5
Revises: cb0c894992e4
Create Date: 2026-04-11 18:08:49.391661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43c8f2f3e6d5'
down_revision: Union[str, Sequence[str], None] = 'cb0c894992e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('reset_password_token', sa.String(length=64), nullable=True))
    op.add_column('usuarios', sa.Column('reset_password_expires_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_usuarios_reset_password_token'), 'usuarios', ['reset_password_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_reset_password_token'), table_name='usuarios')
    op.drop_column('usuarios', 'reset_password_expires_at')
    op.drop_column('usuarios', 'reset_password_token')
    # ### end Alembic commands ###
