"""add_recurrence_and_categories

Revision ID: 4ea29a176023
Revises: 21f5bd31cd3f
Create Date: 2026-03-08 11:53:52.697589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""add_recurrence_and_categories

Revision ID: 4ea29a176023
Revises: 21f5bd31cd3f
Create Date: 2026-03-08 11:53:52.697589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ea29a176023'
down_revision: Union[str, Sequence[str], None] = '21f5bd31cd3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias_financeiras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escritorio_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['escritorio_id'], ['escritorios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_financeiras_id'), 'categorias_financeiras', ['id'], unique=False)
    
    op.create_table('recorrencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escritorio_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('frequencia', sa.String(length=50), nullable=True),
    sa.Column('data_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_fim', sa.DateTime(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['escritorio_id'], ['escritorios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recorrencias_escritorio_id'), 'recorrencias', ['escritorio_id'], unique=False)
    op.create_index(op.f('ix_recorrencias_id'), 'recorrencias', ['id'], unique=False)
    
    op.add_column('transacoes', sa.Column('recorrencia_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_transacoes_recorrencia_id'), 'transacoes', ['recorrencia_id'], unique=False)
    op.create_foreign_key(None, 'transacoes', 'recorrencias', ['recorrencia_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transacoes', type_='foreignkey')
    op.drop_index(op.f('ix_transacoes_recorrencia_id'), table_name='transacoes')
    op.drop_column('transacoes', 'recorrencia_id')
    op.drop_index(op.f('ix_recorrencias_id'), table_name='recorrencias')
    op.drop_index(op.f('ix_recorrencias_escritorio_id'), table_name='recorrencias')
    op.drop_table('recorrencias')
    op.drop_index(op.f('ix_categorias_financeiras_id'), table_name='categorias_financeiras')
    op.drop_table('categorias_financeiras')
    # ### end Alembic commands ###
