"""make cliente_id nullable in documentos_cliente

Revision ID: 8c4e143d54c6
Revises: e7b23d90f1a2
Create Date: 2026-03-03 10:07:43.021304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c4e143d54c6'
down_revision: Union[str, Sequence[str], None] = 'e7b23d90f1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documentos_cliente', 'cliente_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documentos_cliente', 'cliente_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
