"""Add pastas_documento

Revision ID: 9b1f25a5a25d
Revises: 8c4e143d54c6
Create Date: 2026-03-03 15:54:54.678613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b1f25a5a25d'
down_revision: Union[str, Sequence[str], None] = '8c4e143d54c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pastas_documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('escritorio_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('servico_id', sa.Integer(), nullable=True),
    sa.Column('processo_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['escritorio_id'], ['escritorios.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['pastas_documento.id'], ),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pastas_documento_cliente_id'), 'pastas_documento', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_pastas_documento_escritorio_id'), 'pastas_documento', ['escritorio_id'], unique=False)
    op.create_index(op.f('ix_pastas_documento_id'), 'pastas_documento', ['id'], unique=False)
    op.create_index(op.f('ix_pastas_documento_parent_id'), 'pastas_documento', ['parent_id'], unique=False)
    op.create_index(op.f('ix_pastas_documento_servico_id'), 'pastas_documento', ['servico_id'], unique=False)
    op.add_column('documentos_cliente', sa.Column('pasta_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_documentos_cliente_pasta_id'), 'documentos_cliente', ['pasta_id'], unique=False)
    op.create_foreign_key(None, 'documentos_cliente', 'pastas_documento', ['pasta_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documentos_cliente', type_='foreignkey')
    op.drop_index(op.f('ix_documentos_cliente_pasta_id'), table_name='documentos_cliente')
    op.drop_column('documentos_cliente', 'pasta_id')
    op.drop_index(op.f('ix_pastas_documento_servico_id'), table_name='pastas_documento')
    op.drop_index(op.f('ix_pastas_documento_parent_id'), table_name='pastas_documento')
    op.drop_index(op.f('ix_pastas_documento_id'), table_name='pastas_documento')
    op.drop_index(op.f('ix_pastas_documento_escritorio_id'), table_name='pastas_documento')
    op.drop_index(op.f('ix_pastas_documento_cliente_id'), table_name='pastas_documento')
    op.drop_table('pastas_documento')
    # ### end Alembic commands ###
