"""add_data_atualizacao_to_escritorio

Revision ID: cb0c894992e4
Revises: 4ea29a176023
Create Date: 2026-04-10 11:38:41.574950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb0c894992e4'
down_revision: Union[str, Sequence[str], None] = '4ea29a176023'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('escritorios', sa.Column('data_atualizacao', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('escritorios', 'data_atualizacao')
    # ### end Alembic commands ###
