"""Versao inicial 003

Revision ID: d3c3ba90d8d8
Revises: 4db4430b0b72
Create Date: 2026-03-02 16:30:54.978535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3c3ba90d8d8'
down_revision: Union[str, Sequence[str], None] = '4db4430b0b72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('escritorios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('documento', sa.String(length=50), nullable=True),
    sa.Column('logo_path', sa.String(length=255), nullable=True),
    sa.Column('gemini_api_key', sa.String(length=255), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escritorios_id'), 'escritorios', ['id'], unique=False)
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escritorio_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('documento', sa.String(length=50), nullable=True),
    sa.Column('telefone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('cep', sa.String(length=20), nullable=True),
    sa.Column('data_nascimento', sa.String(length=20), nullable=True),
    sa.Column('nacionalidade', sa.String(length=100), nullable=True),
    sa.Column('estado_civil', sa.String(length=50), nullable=True),
    sa.Column('profissao', sa.String(length=100), nullable=True),
    sa.Column('rg', sa.String(length=50), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['escritorio_id'], ['escritorios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_table('modelos_documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escritorio_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('arquivo_path', sa.String(length=300), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['escritorio_id'], ['escritorios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modelos_documento_escritorio_id'), 'modelos_documento', ['escritorio_id'], unique=False)
    op.create_index(op.f('ix_modelos_documento_id'), 'modelos_documento', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escritorio_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('perfil', sa.String(length=50), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('cpf', sa.String(length=20), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['escritorio_id'], ['escritorios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('documentos_cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escritorio_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('arquivo_path', sa.String(length=300), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('token_assinatura', sa.String(length=32), nullable=True),
    sa.Column('status_assinatura', sa.String(length=50), nullable=True),
    sa.Column('arquivo_assinado_path', sa.String(length=500), nullable=True),
    sa.Column('hash_original', sa.String(length=64), nullable=True),
    sa.Column('hash_assinado', sa.String(length=64), nullable=True),
    sa.Column('token_validacao', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['escritorio_id'], ['escritorios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_cliente_cliente_id'), 'documentos_cliente', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_documentos_cliente_escritorio_id'), 'documentos_cliente', ['escritorio_id'], unique=False)
    op.create_index(op.f('ix_documentos_cliente_id'), 'documentos_cliente', ['id'], unique=False)
    op.create_index(op.f('ix_documentos_cliente_token_assinatura'), 'documentos_cliente', ['token_assinatura'], unique=True)
    op.create_index(op.f('ix_documentos_cliente_token_validacao'), 'documentos_cliente', ['token_validacao'], unique=True)
    op.create_table('partes_envolvidas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('escritorio_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('documento', sa.String(length=50), nullable=True),
    sa.Column('papel', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=50), nullable=True),
    sa.Column('rg', sa.String(length=50), nullable=True),
    sa.Column('data_nascimento', sa.String(length=20), nullable=True),
    sa.Column('nacionalidade', sa.String(length=100), nullable=True),
    sa.Column('estado_civil', sa.String(length=50), nullable=True),
    sa.Column('profissao', sa.String(length=100), nullable=True),
    sa.Column('cep', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['escritorio_id'], ['escritorios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partes_envolvidas_id'), 'partes_envolvidas', ['id'], unique=False)
    op.create_table('servicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escritorio_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('tipo_servico_id', sa.Integer(), nullable=True),
    sa.Column('processo_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('valor_total', sa.Float(), nullable=True),
    sa.Column('condicoes_pagamento', sa.Text(), nullable=True),
    sa.Column('forma_pagamento', sa.String(length=100), nullable=True),
    sa.Column('qtd_parcelas', sa.Integer(), nullable=True),
    sa.Column('detalhes_pagamento', sa.Text(), nullable=True),
    sa.Column('porcentagem_exito', sa.String(length=20), nullable=True),
    sa.Column('data_contrato', sa.String(length=20), nullable=True),
    sa.Column('data_contratacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['escritorio_id'], ['escritorios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servicos_id'), 'servicos', ['id'], unique=False)
    op.create_table('signatarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('documento_id', sa.Integer(), nullable=False),
    sa.Column('token_acesso', sa.String(length=32), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('cpf', sa.String(length=20), nullable=True),
    sa.Column('funcao', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('data_visualizacao', sa.DateTime(), nullable=True),
    sa.Column('data_assinatura', sa.DateTime(), nullable=True),
    sa.Column('ip_assinatura', sa.String(length=50), nullable=True),
    sa.Column('user_agent_assinatura', sa.String(length=500), nullable=True),
    sa.Column('tipo_autenticacao', sa.String(length=50), nullable=True),
    sa.Column('imagem_assinatura_path', sa.String(length=300), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('x_pos', sa.Float(), nullable=True),
    sa.Column('y_pos', sa.Float(), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('docwidth', sa.Float(), nullable=True),
    sa.Column('docheight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos_cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signatarios_documento_id'), 'signatarios', ['documento_id'], unique=False)
    op.create_index(op.f('ix_signatarios_id'), 'signatarios', ['id'], unique=False)
    op.create_index(op.f('ix_signatarios_token_acesso'), 'signatarios', ['token_acesso'], unique=True)
    op.create_table('signatarios_posicoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signatario_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('x_pos', sa.Float(), nullable=False),
    sa.Column('y_pos', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('docwidth', sa.Float(), nullable=False),
    sa.Column('docheight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['signatario_id'], ['signatarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signatarios_posicoes_id'), 'signatarios_posicoes', ['id'], unique=False)
    op.create_index(op.f('ix_signatarios_posicoes_signatario_id'), 'signatarios_posicoes', ['signatario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signatarios_posicoes_signatario_id'), table_name='signatarios_posicoes')
    op.drop_index(op.f('ix_signatarios_posicoes_id'), table_name='signatarios_posicoes')
    op.drop_table('signatarios_posicoes')
    op.drop_index(op.f('ix_signatarios_token_acesso'), table_name='signatarios')
    op.drop_index(op.f('ix_signatarios_id'), table_name='signatarios')
    op.drop_index(op.f('ix_signatarios_documento_id'), table_name='signatarios')
    op.drop_table('signatarios')
    op.drop_index(op.f('ix_servicos_id'), table_name='servicos')
    op.drop_table('servicos')
    op.drop_index(op.f('ix_partes_envolvidas_id'), table_name='partes_envolvidas')
    op.drop_table('partes_envolvidas')
    op.drop_index(op.f('ix_documentos_cliente_token_validacao'), table_name='documentos_cliente')
    op.drop_index(op.f('ix_documentos_cliente_token_assinatura'), table_name='documentos_cliente')
    op.drop_index(op.f('ix_documentos_cliente_id'), table_name='documentos_cliente')
    op.drop_index(op.f('ix_documentos_cliente_escritorio_id'), table_name='documentos_cliente')
    op.drop_index(op.f('ix_documentos_cliente_cliente_id'), table_name='documentos_cliente')
    op.drop_table('documentos_cliente')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_modelos_documento_id'), table_name='modelos_documento')
    op.drop_index(op.f('ix_modelos_documento_escritorio_id'), table_name='modelos_documento')
    op.drop_table('modelos_documento')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_escritorios_id'), table_name='escritorios')
    op.drop_table('escritorios')
    # ### end Alembic commands ###
