"""add_oab_origem_projudi_id

Revision ID: ed172c931f0e
Revises: 3db924e97b0e
Create Date: 2026-04-14 15:31:58.150340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed172c931f0e'
down_revision: Union[str, Sequence[str], None] = '3db924e97b0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processos', sa.Column('origem', sa.String(length=50), nullable=True))
    op.add_column('processos', sa.Column('projudi_id', sa.String(length=50), nullable=True))
    op.add_column('usuarios', sa.Column('oab_numero', sa.String(length=20), nullable=True))
    op.add_column('usuarios', sa.Column('oab_uf', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'oab_uf')
    op.drop_column('usuarios', 'oab_numero')
    op.drop_column('processos', 'projudi_id')
    op.drop_column('processos', 'origem')
    # ### end Alembic commands ###
