name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Build do Frontend (Web)
        working-directory: advtools-web
        env:
          VITE_API_URL: "https://api.advtools.com.br"
        run: |
          npm ci
          npm run build

      - name: Build da Landing Page
        working-directory: advtools-landing
        run: |
          npm ci
          npm run build

      - name: Deploy da API e BD na VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Acessando diretório do projeto..."
            cd /var/www/advtools
            
            echo "Garantindo sincronia total com o repositório (Git Reset)..."
            git fetch origin main
            git reset --hard origin/main
            
            echo "Atualizando link do NGINX..."
            sudo ln -sf /var/www/advtools/infra/nginx/advtools.conf /etc/nginx/sites-available/advtools
            sudo ln -sf /etc/nginx/sites-available/advtools /etc/nginx/sites-enabled/advtools
            
            echo "Testando configuração e Recarregando NGINX..."
            sudo nginx -t && sudo systemctl reload nginx
            
            echo "Recriando containers e compilando novidades da API..."
            docker compose -f docker-compose.prod.yml up -d --build
            
            echo "Aguardando containers estabilizarem..."
            sleep 5
            
            echo "Rodando as migrações do Alembic..."
            docker exec advtools-api-prod alembic upgrade head
            
            echo "Deploy da infra concluído!"

      - name: Copia dist do Frontend Web para a VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "advtools-web/dist/*"
          target: "/var/www/advtools/advtools-web/dist"
          strip_components: 2

      - name: Copia dist da Landing Page para a VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "advtools-landing/dist/*"
          target: "/var/www/advtools/advtools-landing/dist"
          strip_components: 2
